### ISSUE TITLE
May I have your clarifications how redis + git work?

### ISSUE THREAD

**Issue by datlife** [soffes/soffes.blog#3]
Hi soffes,

I recently come across your website, particular this [nerd-blog](https://soffes.blog/nerd-blog)  post. I really like the idea of leveraging github + redis as a database, however,  I am still confused after reading your code. Whenever you have time, would you please help me answer following questions?

1. Which file indicates how the program loads contents from `github/soffes/blog` into redis? 
2. If I would like to publish my personal website to github.io, would your approach (`Git` + `Redis` )allow me not having a back-end database server ? (Similar to this [question](https://stackoverflow.com/questions/31655085/database-on-a-personal-github-page) on Stackoverflow ). The reason is there are so many "plug-n-pay" frameworks that I do not want to rely on. 

Thank you for reading and hope you'd have a  good day.

Regards,

P/S: I am new to the web dev,  please excuse my lack of knowledge on this topic. :)

**Comment by soffes** [comment]
Just seeing this 🙃 

1. [This script](https://github.com/soffes/soffes.blog/blob/master/lib/tasks/import.rake) does it
2. No, you still need a backend server to connect to Redis. I'd eventually love to rewrite this as a static site generator instead.
